name: vespa_app
description: "A new Flutter project."

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cached_network_image: ^3.3.1
  cupertino_icons: ^1.0.0
  dio: ^5.4.3+1
  firebase_core: ^3.3.0
  firebase_crashlytics: ^4.0.4
  fl_chart: ^0.68.0
  flutter_dotenv: ^5.1.0
  flutter_image_compress: ^2.1.0
  flutter_inappwebview: ^6.0.0
  flutter_local_notifications: ^17.1.2
  geolocator: ^12.0.0
  get: ^4.6.6
  get_storage: ^2.0.3
  google_maps_flutter: ^2.5.0
  image_picker: ^1.0.4
  intl: ^0.19.0
  month_picker_dialog: ^4.0.1
  onesignal_flutter: ^5.1.6
  path_provider: ^2.0.8
  permission_handler: ^11.0.1
  pretty_dio_logger: ^1.3.1
  shimmer: ^3.0.0
  store_redirect: ^2.0.1
  syncfusion_flutter_calendar: ^26.2.7
  syncfusion_flutter_datepicker: ^26.2.7
  url_launcher: ^6.3.0
  flutter_colorpicker: ^1.1.0
  flutter_gen: ^5.10.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  # generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
